// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChROQWlcSuowyplqFTE-ti74FvnBl-OKo',
    appId: '1:1099301995454:web:bc0b4ef18054989e3e6fef',
    messagingSenderId: '1099301995454',
    projectId: 'collaborativeprogress-3c62b',
    authDomain: 'collaborativeprogress-3c62b.firebaseapp.com',
    storageBucket: 'collaborativeprogress-3c62b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPL0st4haYGsv1rTfhFHthYLjXwBUhfik',
    appId: '1:1099301995454:android:d6524f20ba97d3c23e6fef',
    messagingSenderId: '1099301995454',
    projectId: 'collaborativeprogress-3c62b',
    storageBucket: 'collaborativeprogress-3c62b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx0hfPnNjmDcRuuax040Yyx8B8Mu7h5ek',
    appId: '1:1099301995454:ios:d912b326f9a5a7e53e6fef',
    messagingSenderId: '1099301995454',
    projectId: 'collaborativeprogress-3c62b',
    storageBucket: 'collaborativeprogress-3c62b.appspot.com',
    iosBundleId: 'com.example.collabProg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx0hfPnNjmDcRuuax040Yyx8B8Mu7h5ek',
    appId: '1:1099301995454:ios:d912b326f9a5a7e53e6fef',
    messagingSenderId: '1099301995454',
    projectId: 'collaborativeprogress-3c62b',
    storageBucket: 'collaborativeprogress-3c62b.appspot.com',
    iosBundleId: 'com.example.collabProg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChROQWlcSuowyplqFTE-ti74FvnBl-OKo',
    appId: '1:1099301995454:web:78136c2f7d8009243e6fef',
    messagingSenderId: '1099301995454',
    projectId: 'collaborativeprogress-3c62b',
    authDomain: 'collaborativeprogress-3c62b.firebaseapp.com',
    storageBucket: 'collaborativeprogress-3c62b.appspot.com',
  );
}
